// Grouped by AHA ACLS required rhythm categories (Oct 2025 Pre-Course Self-Assessment)

export const SCENARIO_GROUPS = [
  { key: 'arrest', label: 'Arrest Rhythms'  },
  { key: 'tachy',  label: 'Tachycardias'    },
  { key: 'brady',  label: 'Bradycardias'    },
  { key: 'normal', label: 'Normal / Baseline' },
]

export const SCENARIOS = [

  // ── ARREST RHYTHMS ──────────────────────────────────────────────────────────
  // Covers: VF, PEA, Asystole/Agonal, Pulseless VT (mono), Polymorphic VT
  {
    id: 'vf_arrest',
    group: 'arrest',
    name: 'VF Arrest — 58yo Male',
    description: 'Unresponsive, pulseless, found on floor.',
    rhythm: 'VFIB',
    captureThreshold: 999,
    vitals: { hr: 0, sbp: 0, dbp: 0, spo2: 0, etco2: 10, temp: 98.2 },
    vitalsHidden: false,
  },
  {
    id: 'pea_arrest',
    group: 'arrest',
    name: 'PEA Arrest — 44yo Female',
    description: 'Post-op, collapsed. Organized rhythm on monitor, no pulse on check.',
    rhythm: 'PEA',
    captureThreshold: 999,
    vitals: { hr: 60, sbp: 0, dbp: 0, spo2: 0, etco2: 8, temp: 97.8 },
    vitalsHidden: false,
  },
  {
    id: 'asystole',
    group: 'arrest',
    name: 'Asystole — 71yo Male',
    description: 'Found unresponsive in hallway, apneic, no pulse. Flatline on monitor.',
    rhythm: 'ASYSTOLE',
    captureThreshold: 999,
    vitals: { hr: 0, sbp: 0, dbp: 0, spo2: 0, etco2: 5, temp: 97.6 },
    vitalsHidden: false,
  },
  {
    id: 'vtach_pulseless',
    group: 'arrest',
    name: 'Pulseless VTach — 48yo Male',
    description: 'Collapsed during exercise. Wide-complex tachycardia on monitor, no pulse confirmed.',
    rhythm: 'VTACH',
    captureThreshold: 999,
    vitals: { hr: 165, sbp: 0, dbp: 0, spo2: 0, etco2: 12, temp: 98.6 },
    vitalsHidden: false,
  },
  {
    id: 'torsades',
    group: 'arrest',
    name: 'Torsades — 49yo Female',
    description: 'Known long QT syndrome. Pulseless polymorphic VT, twisting-of-the-points pattern.',
    rhythm: 'TORSADES',
    captureThreshold: 999,
    vitals: { hr: 0, sbp: 0, dbp: 0, spo2: 0, etco2: 5, temp: 98.0 },
    vitalsHidden: false,
  },

  // ── TACHYCARDIAS ─────────────────────────────────────────────────────────────
  // Covers: SVT/narrow-complex, Stable VT (mono), AFib, AFlutter, Sinus Tach
  {
    id: 'svt_unstable',
    group: 'tachy',
    name: 'Unstable SVT — 37yo Female',
    description: 'Sudden chest pain and dizziness. HR 190, BP 86/54, diaphoretic.',
    rhythm: 'SVT',
    captureThreshold: 60,
    vitals: { hr: 190, sbp: 86, dbp: 54, spo2: 94, etco2: 32, temp: 98.6 },
    vitalsHidden: true,
  },
  {
    id: 'vtach_pulse',
    group: 'tachy',
    name: 'VTach with Pulse — 55yo Male',
    description: 'Palpitations, diaphoretic. Wide-complex regular tachycardia, BP 100/60, pulse present.',
    rhythm: 'VTACH',
    captureThreshold: 60,
    vitals: { hr: 160, sbp: 100, dbp: 60, spo2: 93, etco2: 30, temp: 98.6 },
    vitalsHidden: true,
  },
  {
    id: 'afib_rvr',
    group: 'tachy',
    name: 'AFib with RVR — 72yo Male',
    description: 'Palpitations. Irregularly irregular rhythm, HR 115–140, BP 108/70.',
    rhythm: 'AFIB',
    captureThreshold: 60,
    vitals: { hr: 124, sbp: 108, dbp: 70, spo2: 96, etco2: 34, temp: 98.8 },
    vitalsHidden: true,
  },
  {
    id: 'aflutter',
    group: 'tachy',
    name: 'Atrial Flutter — 65yo Male',
    description: 'Palpitations x 2 days. Sawtooth flutter waves, 2:1 AV conduction, ventricular rate 150.',
    rhythm: 'AFLUTTER',
    captureThreshold: 60,
    vitals: { hr: 150, sbp: 110, dbp: 72, spo2: 95, etco2: 33, temp: 98.6 },
    vitalsHidden: true,
  },
  {
    id: 'sinus_tach',
    group: 'tachy',
    name: 'Sinus Tachycardia — 32yo Male',
    description: 'MVC with suspected internal hemorrhage. HR 118, BP 88/54, pale and diaphoretic.',
    rhythm: 'SINUS_TACH',
    captureThreshold: 60,
    vitals: { hr: 118, sbp: 88, dbp: 54, spo2: 96, etco2: 31, temp: 98.4 },
    vitalsHidden: true,
  },

  // ── BRADYCARDIAS ─────────────────────────────────────────────────────────────
  // Covers: Sinus Brady, Wenckebach (Mobitz I), Mobitz II, 3rd Degree (Complete Block)
  {
    id: 'sinus_brady_sym',
    group: 'brady',
    name: 'Symptomatic Brady — 80yo Female',
    description: 'Weakness, dizziness, near-syncope. HR 38, BP 88/60.',
    rhythm: 'SINUS_BRADY',
    captureThreshold: 60,
    vitals: { hr: 38, sbp: 88, dbp: 60, spo2: 93, etco2: 29, temp: 97.2 },
    vitalsHidden: true,
  },
  {
    id: 'wenckebach',
    group: 'brady',
    name: 'Wenckebach (Mobitz I) — 70yo Male',
    description: 'Near-syncope. Progressive PR lengthening with periodically dropped QRS.',
    rhythm: 'WENCKEBACH',
    captureThreshold: 60,
    vitals: { hr: 48, sbp: 96, dbp: 64, spo2: 94, etco2: 30, temp: 97.8 },
    vitalsHidden: true,
  },
  {
    id: 'mobitz2',
    group: 'brady',
    name: 'Mobitz II — 58yo Male',
    description: 'Pre-syncope. Constant PR interval with intermittent non-conducted P waves.',
    rhythm: 'MOBITZ2',
    captureThreshold: 60,
    vitals: { hr: 45, sbp: 90, dbp: 60, spo2: 93, etco2: 28, temp: 97.8 },
    vitalsHidden: true,
  },
  {
    id: 'complete_block',
    group: 'brady',
    name: 'Complete Block — 68yo Male',
    description: 'Syncope. AV dissociation, ventricular escape rate 35, BP 72/48.',
    rhythm: 'THIRD_DEGREE',
    captureThreshold: 40,
    vitals: { hr: 35, sbp: 72, dbp: 48, spo2: 91, etco2: 28, temp: 97.4 },
    vitalsHidden: true,
  },

  // ── NORMAL / BASELINE ────────────────────────────────────────────────────────
  // Covers: NSR (required), plus NSR variants for additional teaching
  {
    id: 'nsr_baseline',
    group: 'normal',
    name: 'NSR Baseline — 54yo Male',
    description: 'Post-ROSC monitoring. Stable, appropriate rate and rhythm.',
    rhythm: 'NSR',
    captureThreshold: 60,
    vitals: { hr: 78, sbp: 118, dbp: 76, spo2: 97, etco2: 36, temp: 98.2 },
    vitalsHidden: false,
  },
  {
    id: 'stemi',
    group: 'normal',
    name: 'Inferior STEMI — 61yo Male',
    description: 'Crushing chest pain radiating to jaw, diaphoretic. ST elevation in inferior leads.',
    rhythm: 'NSR_STEMI',
    captureThreshold: 60,
    vitals: { hr: 78, sbp: 94, dbp: 62, spo2: 95, etco2: 33, temp: 98.4 },
    vitalsHidden: true,
  },
]
